from PySide6.QtCore import QObject, Signal

class BlocklyManager(QObject):
    # Signals
    code_generated = Signal(str)
    execution_step = Signal(str, int) # block_id, status

    def __init__(self):
        super().__init__()

    def export_to_python(self, blocks_list):
        """
        Converts the visual block nodes into an executable python control script.
        """
        code_lines = [
            "# Generated by DroneEduAI Visual Programmer",
            "import time",
            "from drone_api import UAVController",
            "",
            "drone = UAVController()",
            "drone.connect()",
            ""
        ]
        
        for idx, block in enumerate(blocks_list):
            name = block.get("name", "Unknown")
            duration = block.get("duration", 2.0)
            
            if name == "Takeoff":
                code_lines.append(f"drone.takeoff(alt=1.5)\ntime.sleep({duration})")
            elif name == "Land":
                code_lines.append(f"drone.land()\ntime.sleep({duration})")
            elif name == "Hover":
                code_lines.append(f"drone.hover()\ntime.sleep({duration})")
            elif name == "Forward":
                code_lines.append(f"drone.move_forward(speed=0.5)\ntime.sleep({duration})")
            elif name == "Backward":
                code_lines.append(f"drone.move_backward(speed=0.5)\ntime.sleep({duration})")
            elif name == "Turn Right":
                code_lines.append(f"drone.turn_right(angle=90)\ntime.sleep({duration})")
            elif name == "Turn Left":
                code_lines.append(f"drone.turn_left(angle=90)\ntime.sleep({duration})")
            elif name == "Up":
                code_lines.append(f"drone.move_up(speed=0.3)\ntime.sleep({duration})")
            elif name == "Down":
                code_lines.append(f"drone.move_down(speed=0.3)\ntime.sleep({duration})")
            else:
                code_lines.append(f"# Custom block: {name}\ntime.sleep({duration})")
                
        code_lines.append("\ndrone.disconnect()")
        full_code = "\n".join(code_lines)
        self.code_generated.emit(full_code)
        return full_code
